### ISSUE TITLE
problem with ARM architecture?

### ISSUE THREAD

**Issue by hadmut** [dlenski/python-vipaccess#19]
Hi, 
I just tried it on Ubuntu 18.04 on a regular x86 machine,  sudo pip3 install python-vipaccess and vipaccess provision -p -t VSMT   runs as expected, success. 

When doing the same on a Raspberry Pi with latest Raspbian, I get the error message

Something went wrong--the token is invalid.

**Comment by TotallyInformation** [comment]
I've also just run from a Pi3 and got:

```
pi@pi3:~/python-vipaccess $ pip install .
Processing /home/pi/python-vipaccess
Collecting lxml==4.2.5 (from python-vipaccess==0.3.1)
From cffi callback <function _verify_callback at 0x76cbb430>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
From cffi callback <function _verify_callback at 0x756663b0>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement lxml==4.2.5 (from python-vipaccess==0.3.1) (from versions: )
No matching distribution found for lxml==4.2.5 (from python-vipaccess==0.3.1)
```

I tried to manually install `lxml` either from pip or apt and neither works.

**Comment by TotallyInformation** [comment]
From a hint on another site, I've discovered that you can install the lxml dependency if you use pip3 instead of pip.

It would be tremendously helpful if the instructions for manual installation could be updated to the correct ones. Not all of us have ready access to a Docker environment.

In the meantime, I've documented the whole thing - and a way to completely avoid needing this tool - on my blog.

https://it.knightnet.org.uk/blog/use-an-authenticator-app-to-login-to-paypal/

**Comment by dlenski** [comment]
> From a hint on another site, I've discovered that you can install the lxml dependency if you use pip3 instead of pip.

**Either** Python 2.7 or 3.3+ should work fine. If the distribution's version of Python 2.7 isn't working for you, I think that's a problem with the distribution, and _not_ with this program.

Or am I misunderstanding here? I'm not really clear on what the problem is or what you think should be changed.

**Comment by dlenski** [comment]
In fact, the `.travis-ci.yml` build/test script _verifies_ that it can be built, dependencies installed, and token generated successfully… including on Python 2.7.

**Comment by TotallyInformation** [comment]
Well, I'm not a Python expert so it is hard to know what is causing the issue. However `lxml==4.2.5` seems to be the issue. I tried to find a Python 2.7 version of lxml and it couldn't be found even on PIP or at least not that exact version.

**Comment by dlenski** [comment]
> However lxml==4.2.5 seems to be the issue.

Thanks. I just tested it and lxml 3.5.0 (as distributed by Ubuntu 18.04) seems to work just fine. So I'm going to tweak the `requirements.txt`. Maybe that'll allow you to build with Python 2.7?

**Comment by dlenski** [comment]
Closing due to inactivity.
