### ISSUE TITLE
Errors when creating HOTP token

### ISSUE THREAD

**Issue by NeighborGeek** [dlenski/python-vipaccess#27]
I'm trying to create HOTP based tokens using a different token model.  I was able to successfully create one using the docker image, but did get a message in the output that something went wrong and the token couldn't be validated.  If you're validating based on time, that would make sense. 

When I tried installing python-vipaccess on a computer directly and generating a key using the same command, it's throwing errors rather than giving me the key info.  If I use a token type of VSMT it works fine.  Here's what I'm seeing when I try to use UBHE: 
```
c:\ProgramFiles\python-3.5.3\Scripts>vipaccess.exe provision -p -t UBHE
Generating request...
Fetching provisioning response...
Getting token from response...
Traceback (most recent call last):
  File "c:\ProgramFiles\python-3.5.3\Scripts\vipaccess-script.py", line 11, in <module>
    load_entry_point('python-vipaccess==0.3.1', 'console_scripts', 'vipaccess')()
  File "c:\programfiles\python-3.5.3\lib\site-packages\python_vipaccess-0.3.1-py3.5.egg\vipaccess\cli.py", line 174, in main
  File "c:\programfiles\python-3.5.3\lib\site-packages\python_vipaccess-0.3.1-py3.5.egg\vipaccess\cli.py", line 52, in provision
  File "c:\programfiles\python-3.5.3\lib\site-packages\python_vipaccess-0.3.1-py3.5.egg\vipaccess\provision.py", line 142, in get_token_from_response
AttributeError: 'NoneType' object has no attribute 'text'
```

Am I doing something wrong, or has something changed between version in the image from dockerhub and the current version?

**Comment by dlenski** [comment]
Good report, thank you. :+1: 

> Am I doing something wrong, or has something changed between version in the image from dockerhub and the current version?

The short answer is “probably yes,” and I'm working on a fix now. (For what it's worth, I do **not** use dockerhub or have any control over the version there.)
