### ISSUE TITLE
The version number in setup.py is not up to date

### ISSUE THREAD

**Issue by Kodiologist** [dlenski/python-vipaccess#28]
Thus, `pip3 install https://github.com/dlenski/python-vipaccess/archive/v0.10.0.zip` followed by `pip3 show python-vipaccess` produces `Version: 0.3.1`.

**Comment by Kodiologist** [comment]
Relatedly, the latest version on PyPI seems to be quite old.

**Comment by dlenski** [comment]
Fixed both.

**Comment by Kodiologist** [comment]
You're welcome. Is it possible that the wrong file was uploaded to PyPI? I'm getting an error when I try `pip3 install --upgrade python-vipaccess`:

```Collecting python-vipaccess
  Downloading https://files.pythonhosted.org/packages/11/c9/51bb2b194f93477972da71b44d65dcfb56d2bb2ec27f531af1a9e3586ccc/python-vipaccess-0.10.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0linvjoa/python-vipaccess/setup.py", line 4, in <module>
        with open('description.rst', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'description.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-0linvjoa/python-vipaccess/```
