### ISSUE TITLE
Provisioning fails with "Malformed request"

### ISSUE THREAD

**Issue by diggernet** [dlenski/python-vipaccess#67]
Using version 0.14.1:

$ vipaccess provision -p -t SYMC/VSMT

Generating request...
Fetching provisioning response from Symantec server...
Getting token from response...
Traceback (most recent call last):
  File "/[...]/bin/vipaccess", line 8, in <module>
    sys.exit(main())
  File "/[...]/lib/python3.10/site-packages/vipaccess/__main__.py", line 242, in main
    return args.func(p, args)
  File "/[...]/lib/python3.10/site-packages/vipaccess/__main__.py", line 54, in provision
    otp_token = vp.get_token_from_response(response.content)
  File "/[...]/lib/python3.10/site-packages/vipaccess/provision.py", line 127, in get_token_from_response
    raise RuntimeError(result, reasoncode)
RuntimeError: ('Malformed request', '4E00')

The response XML is:
<?xml version="1.0" encoding="UTF-8"?>\n<GetSharedSecretResponse RequestId="1680543615" Version="2.0" xmlns="http://www.verisign.com/2006/08/vipservice">\n  <Status>\n    <ReasonCode>4E00</ReasonCode>\n    <StatusMessage>Malformed request</StatusMessage>\n  </Status>\n</GetSharedSecretResponse>

**Comment by diggernet** [comment]
Ok, nevermind...  I was confused by this text in help:

> VIP Access token model. Often SYMC/VSMT ("mobile" token, default) or SYDC/VSST
> ("desktop" token). Some clients only accept one or the other. Other more obscure
> token types also exist: https://support.symantec.com/en_US/article.TECH239895.html

It appears to work fine using "-t SYMC", as I saw mentioned on another site.
